name: Deploy Hexo Blog to Cloud Server

on:
  push:
    branches:
      - main  # 可根据你博客源码的分支修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npx hexo generate

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 114.132.122.142 >> ~/.ssh/known_hosts

      - name: Deploy to cloud server via SCP
        run: |
          scp -r ./public/* root@114.132.122.142:/home/webapps/blog/
