name: Hexo Deploy to Server

on:
  push:
    branches:
      - main  # 或你博客源码的分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Hexo Site
        run: npx hexo generate

      - name: Deploy to Server via SCP and reload pm2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "public/*"
          target: "/home/webapps/blog/"
          rm: true  # 删除目标目录下旧文件再上传（谨慎使用）

      - name: Reload pm2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: pm2 reload hexo-blog
